//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.15 at 07:30:28 PM CET 
//


package com.ricardogarfe.renfe.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for DatosPeticionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DatosPeticionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Origen" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Destino" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="FechaViaje" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="Intervalo" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Desde" type="{http://www.w3.org/2001/XMLSchema}time" minOccurs="0"/>
 *                   &lt;element name="Hasta" type="{http://www.w3.org/2001/XMLSchema}time" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DatosPeticionType", propOrder = {
    "origen",
    "destino",
    "fechaViaje",
    "intervalo"
})
public class DatosPeticionType {

    @XmlElement(name = "Origen", required = true)
    protected String origen;
    @XmlElement(name = "Destino", required = true)
    protected String destino;
    @XmlElement(name = "FechaViaje")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fechaViaje;
    @XmlElement(name = "Intervalo")
    protected DatosPeticionType.Intervalo intervalo;

    /**
     * Gets the value of the origen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrigen() {
        return origen;
    }

    /**
     * Sets the value of the origen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrigen(String value) {
        this.origen = value;
    }

    /**
     * Gets the value of the destino property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestino() {
        return destino;
    }

    /**
     * Sets the value of the destino property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestino(String value) {
        this.destino = value;
    }

    /**
     * Gets the value of the fechaViaje property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaViaje() {
        return fechaViaje;
    }

    /**
     * Sets the value of the fechaViaje property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaViaje(XMLGregorianCalendar value) {
        this.fechaViaje = value;
    }

    /**
     * Gets the value of the intervalo property.
     * 
     * @return
     *     possible object is
     *     {@link DatosPeticionType.Intervalo }
     *     
     */
    public DatosPeticionType.Intervalo getIntervalo() {
        return intervalo;
    }

    /**
     * Sets the value of the intervalo property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatosPeticionType.Intervalo }
     *     
     */
    public void setIntervalo(DatosPeticionType.Intervalo value) {
        this.intervalo = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Desde" type="{http://www.w3.org/2001/XMLSchema}time" minOccurs="0"/>
     *         &lt;element name="Hasta" type="{http://www.w3.org/2001/XMLSchema}time" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "desde",
        "hasta"
    })
    public static class Intervalo {

        @XmlElement(name = "Desde")
        @XmlSchemaType(name = "time")
        protected XMLGregorianCalendar desde;
        @XmlElement(name = "Hasta")
        @XmlSchemaType(name = "time")
        protected XMLGregorianCalendar hasta;

        /**
         * Gets the value of the desde property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDesde() {
            return desde;
        }

        /**
         * Sets the value of the desde property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDesde(XMLGregorianCalendar value) {
            this.desde = value;
        }

        /**
         * Gets the value of the hasta property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getHasta() {
            return hasta;
        }

        /**
         * Sets the value of the hasta property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setHasta(XMLGregorianCalendar value) {
            this.hasta = value;
        }

    }

}
