//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.15 at 07:30:28 PM CET 
//


package com.ricardogarfe.renfe.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for HorarioType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HorarioType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Linea" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="HoraSalida" type="{http://www.w3.org/2001/XMLSchema}time" minOccurs="0"/>
 *         &lt;element name="Transbordo" type="{}TransbordoType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="HoraLlegada" type="{http://www.w3.org/2001/XMLSchema}time" minOccurs="0"/>
 *         &lt;element name="Duracion" type="{http://www.w3.org/2001/XMLSchema}time" minOccurs="0"/>
 *         &lt;element name="CodCivis" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HorarioType", propOrder = {
    "linea",
    "horaSalida",
    "transbordo",
    "horaLlegada",
    "duracion",
    "codCivis"
})
public class HorarioType {

    @XmlElementRef(name = "Linea", type = JAXBElement.class)
    protected JAXBElement<String> linea;
    @XmlElementRef(name = "HoraSalida", type = JAXBElement.class)
    protected JAXBElement<XMLGregorianCalendar> horaSalida;
    @XmlElement(name = "Transbordo")
    protected List<TransbordoType> transbordo;
    @XmlElementRef(name = "HoraLlegada", type = JAXBElement.class)
    protected JAXBElement<XMLGregorianCalendar> horaLlegada;
    @XmlElementRef(name = "Duracion", type = JAXBElement.class)
    protected JAXBElement<XMLGregorianCalendar> duracion;
    @XmlElementRef(name = "CodCivis", type = JAXBElement.class)
    protected JAXBElement<String> codCivis;

    /**
     * Gets the value of the linea property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getLinea() {
        return linea;
    }

    /**
     * Sets the value of the linea property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setLinea(JAXBElement<String> value) {
        this.linea = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the horaSalida property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getHoraSalida() {
        return horaSalida;
    }

    /**
     * Sets the value of the horaSalida property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setHoraSalida(JAXBElement<XMLGregorianCalendar> value) {
        this.horaSalida = ((JAXBElement<XMLGregorianCalendar> ) value);
    }

    /**
     * Gets the value of the transbordo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the transbordo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTransbordo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TransbordoType }
     * 
     * 
     */
    public List<TransbordoType> getTransbordo() {
        if (transbordo == null) {
            transbordo = new ArrayList<TransbordoType>();
        }
        return this.transbordo;
    }

    /**
     * Gets the value of the horaLlegada property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getHoraLlegada() {
        return horaLlegada;
    }

    /**
     * Sets the value of the horaLlegada property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setHoraLlegada(JAXBElement<XMLGregorianCalendar> value) {
        this.horaLlegada = ((JAXBElement<XMLGregorianCalendar> ) value);
    }

    /**
     * Gets the value of the duracion property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getDuracion() {
        return duracion;
    }

    /**
     * Sets the value of the duracion property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setDuracion(JAXBElement<XMLGregorianCalendar> value) {
        this.duracion = ((JAXBElement<XMLGregorianCalendar> ) value);
    }

    /**
     * Gets the value of the codCivis property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCodCivis() {
        return codCivis;
    }

    /**
     * Sets the value of the codCivis property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCodCivis(JAXBElement<String> value) {
        this.codCivis = ((JAXBElement<String> ) value);
    }

}
