//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.15 at 07:30:28 PM CET 
//


package com.ricardogarfe.renfe.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ricardogarfe.renfe.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _HorarioTypeHoraLlegada_QNAME = new QName("", "HoraLlegada");
    private final static QName _HorarioTypeLinea_QNAME = new QName("", "Linea");
    private final static QName _HorarioTypeDuracion_QNAME = new QName("", "Duracion");
    private final static QName _HorarioTypeCodCivis_QNAME = new QName("", "CodCivis");
    private final static QName _HorarioTypeHoraSalida_QNAME = new QName("", "HoraSalida");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ricardogarfe.renfe.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PeticionHorarios.Horarios }
     * 
     */
    public PeticionHorarios.Horarios createPeticionHorariosHorarios() {
        return new PeticionHorarios.Horarios();
    }

    /**
     * Create an instance of {@link DatosPeticionType.Intervalo }
     * 
     */
    public DatosPeticionType.Intervalo createDatosPeticionTypeIntervalo() {
        return new DatosPeticionType.Intervalo();
    }

    /**
     * Create an instance of {@link HorarioType }
     * 
     */
    public HorarioType createHorarioType() {
        return new HorarioType();
    }

    /**
     * Create an instance of {@link ValidezType }
     * 
     */
    public ValidezType createValidezType() {
        return new ValidezType();
    }

    /**
     * Create an instance of {@link PeticionHorarios }
     * 
     */
    public PeticionHorarios createPeticionHorarios() {
        return new PeticionHorarios();
    }

    /**
     * Create an instance of {@link DatosPeticionType }
     * 
     */
    public DatosPeticionType createDatosPeticionType() {
        return new DatosPeticionType();
    }

    /**
     * Create an instance of {@link TransbordoType }
     * 
     */
    public TransbordoType createTransbordoType() {
        return new TransbordoType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "HoraLlegada", scope = HorarioType.class)
    public JAXBElement<XMLGregorianCalendar> createHorarioTypeHoraLlegada(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_HorarioTypeHoraLlegada_QNAME, XMLGregorianCalendar.class, HorarioType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Linea", scope = HorarioType.class)
    public JAXBElement<String> createHorarioTypeLinea(String value) {
        return new JAXBElement<String>(_HorarioTypeLinea_QNAME, String.class, HorarioType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Duracion", scope = HorarioType.class)
    public JAXBElement<XMLGregorianCalendar> createHorarioTypeDuracion(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_HorarioTypeDuracion_QNAME, XMLGregorianCalendar.class, HorarioType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CodCivis", scope = HorarioType.class)
    public JAXBElement<String> createHorarioTypeCodCivis(String value) {
        return new JAXBElement<String>(_HorarioTypeCodCivis_QNAME, String.class, HorarioType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "HoraSalida", scope = HorarioType.class)
    public JAXBElement<XMLGregorianCalendar> createHorarioTypeHoraSalida(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_HorarioTypeHoraSalida_QNAME, XMLGregorianCalendar.class, HorarioType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "HoraLlegada", scope = TransbordoType.class)
    public JAXBElement<XMLGregorianCalendar> createTransbordoTypeHoraLlegada(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_HorarioTypeHoraLlegada_QNAME, XMLGregorianCalendar.class, TransbordoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Linea", scope = TransbordoType.class)
    public JAXBElement<String> createTransbordoTypeLinea(String value) {
        return new JAXBElement<String>(_HorarioTypeLinea_QNAME, String.class, TransbordoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "HoraSalida", scope = TransbordoType.class)
    public JAXBElement<XMLGregorianCalendar> createTransbordoTypeHoraSalida(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_HorarioTypeHoraSalida_QNAME, XMLGregorianCalendar.class, TransbordoType.class, value);
    }

}
