//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.15 at 07:30:28 PM CET 
//


package com.ricardogarfe.renfe.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Error" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Fecha" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="Validez" type="{}ValidezType" minOccurs="0"/>
 *         &lt;element name="Peticion" type="{}DatosPeticionType" minOccurs="0"/>
 *         &lt;element name="Horarios" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Horario" type="{}HorarioType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "error",
    "fecha",
    "validez",
    "peticion",
    "horarios"
})
@XmlRootElement(name = "PeticionHorarios")
public class PeticionHorarios {

    @XmlElement(name = "Error")
    protected String error;
    @XmlElement(name = "Fecha")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar fecha;
    @XmlElement(name = "Validez")
    protected ValidezType validez;
    @XmlElement(name = "Peticion")
    protected DatosPeticionType peticion;
    @XmlElement(name = "Horarios")
    protected PeticionHorarios.Horarios horarios;

    /**
     * Gets the value of the error property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getError() {
        return error;
    }

    /**
     * Sets the value of the error property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setError(String value) {
        this.error = value;
    }

    /**
     * Gets the value of the fecha property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFecha() {
        return fecha;
    }

    /**
     * Sets the value of the fecha property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFecha(XMLGregorianCalendar value) {
        this.fecha = value;
    }

    /**
     * Gets the value of the validez property.
     * 
     * @return
     *     possible object is
     *     {@link ValidezType }
     *     
     */
    public ValidezType getValidez() {
        return validez;
    }

    /**
     * Sets the value of the validez property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValidezType }
     *     
     */
    public void setValidez(ValidezType value) {
        this.validez = value;
    }

    /**
     * Gets the value of the peticion property.
     * 
     * @return
     *     possible object is
     *     {@link DatosPeticionType }
     *     
     */
    public DatosPeticionType getPeticion() {
        return peticion;
    }

    /**
     * Sets the value of the peticion property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatosPeticionType }
     *     
     */
    public void setPeticion(DatosPeticionType value) {
        this.peticion = value;
    }

    /**
     * Gets the value of the horarios property.
     * 
     * @return
     *     possible object is
     *     {@link PeticionHorarios.Horarios }
     *     
     */
    public PeticionHorarios.Horarios getHorarios() {
        return horarios;
    }

    /**
     * Sets the value of the horarios property.
     * 
     * @param value
     *     allowed object is
     *     {@link PeticionHorarios.Horarios }
     *     
     */
    public void setHorarios(PeticionHorarios.Horarios value) {
        this.horarios = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Horario" type="{}HorarioType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "horario"
    })
    public static class Horarios {

        @XmlElement(name = "Horario", required = true)
        protected List<HorarioType> horario;

        /**
         * Gets the value of the horario property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the horario property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getHorario().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link HorarioType }
         * 
         * 
         */
        public List<HorarioType> getHorario() {
            if (horario == null) {
                horario = new ArrayList<HorarioType>();
            }
            return this.horario;
        }

    }

}
