//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.15 at 07:30:15 PM CET 
//


package com.ricardogarfe.renfe.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Nucleo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Estaciones" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Estacion" type="{}EstacionType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nucleo",
    "estaciones"
})
@XmlRootElement(name = "PeticionEstaciones")
public class PeticionEstaciones {

    @XmlElement(name = "Nucleo", required = true)
    protected String nucleo;
    @XmlElement(name = "Estaciones")
    protected PeticionEstaciones.Estaciones estaciones;

    /**
     * Gets the value of the nucleo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNucleo() {
        return nucleo;
    }

    /**
     * Sets the value of the nucleo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNucleo(String value) {
        this.nucleo = value;
    }

    /**
     * Gets the value of the estaciones property.
     * 
     * @return
     *     possible object is
     *     {@link PeticionEstaciones.Estaciones }
     *     
     */
    public PeticionEstaciones.Estaciones getEstaciones() {
        return estaciones;
    }

    /**
     * Sets the value of the estaciones property.
     * 
     * @param value
     *     allowed object is
     *     {@link PeticionEstaciones.Estaciones }
     *     
     */
    public void setEstaciones(PeticionEstaciones.Estaciones value) {
        this.estaciones = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Estacion" type="{}EstacionType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "estacion"
    })
    public static class Estaciones {

        @XmlElement(name = "Estacion", required = true)
        protected List<EstacionType> estacion;

        /**
         * Gets the value of the estacion property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the estacion property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEstacion().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link EstacionType }
         * 
         * 
         */
        public List<EstacionType> getEstacion() {
            if (estacion == null) {
                estacion = new ArrayList<EstacionType>();
            }
            return this.estacion;
        }

    }

}
