//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.15 at 07:30:28 PM CET 
//


package com.ricardogarfe.renfe.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for TransbordoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TransbordoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Enlace" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="HoraLlegada" type="{http://www.w3.org/2001/XMLSchema}time" minOccurs="0"/>
 *         &lt;element name="HoraSalida" type="{http://www.w3.org/2001/XMLSchema}time" minOccurs="0"/>
 *         &lt;element name="Linea" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TransbordoType", propOrder = {
    "enlace",
    "horaLlegada",
    "horaSalida",
    "linea"
})
public class TransbordoType {

    @XmlElement(name = "Enlace")
    protected String enlace;
    @XmlElementRef(name = "HoraLlegada", type = JAXBElement.class)
    protected JAXBElement<XMLGregorianCalendar> horaLlegada;
    @XmlElementRef(name = "HoraSalida", type = JAXBElement.class)
    protected JAXBElement<XMLGregorianCalendar> horaSalida;
    @XmlElementRef(name = "Linea", type = JAXBElement.class)
    protected JAXBElement<String> linea;

    /**
     * Gets the value of the enlace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnlace() {
        return enlace;
    }

    /**
     * Sets the value of the enlace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnlace(String value) {
        this.enlace = value;
    }

    /**
     * Gets the value of the horaLlegada property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getHoraLlegada() {
        return horaLlegada;
    }

    /**
     * Sets the value of the horaLlegada property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setHoraLlegada(JAXBElement<XMLGregorianCalendar> value) {
        this.horaLlegada = ((JAXBElement<XMLGregorianCalendar> ) value);
    }

    /**
     * Gets the value of the horaSalida property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getHoraSalida() {
        return horaSalida;
    }

    /**
     * Sets the value of the horaSalida property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setHoraSalida(JAXBElement<XMLGregorianCalendar> value) {
        this.horaSalida = ((JAXBElement<XMLGregorianCalendar> ) value);
    }

    /**
     * Gets the value of the linea property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getLinea() {
        return linea;
    }

    /**
     * Sets the value of the linea property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setLinea(JAXBElement<String> value) {
        this.linea = ((JAXBElement<String> ) value);
    }

}
